- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
     msg: "hello {{course | default('ansible')}}"

  - name: number in UPPERCASE
    vars:
     greetings: "hello, goodmorning"
    ansible.builtin.debug:
     msg: "{{greetings | upper}}"