- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
     msg: "hello {{course | default('ansible')}}"

  - name: number in UPPERCASE
    vars:
     greetings: "hello, goodmorning"
    ansible.builtin.debug:
     msg: "{{greetings | upper}}"

  - name: remove duplicates
    vars:
     numbers: [1,2,2,3,4,5]
    ansible.builtin.debug:
     msg: "{{numbers | unique}}"

  - name: print max and min
    vars:
     ages: [20,30,50]
    ansible.builtin.debug:
     msg: "min age: {{ages | min}}, max age: {{ages | max}}"
    