# - name: demo on loops
#   hosts: localhost
#   tasks:
#   - name: print names
#     ansible.builtin.debug:
#      msg: "hello {{item}}"
#     loop:
#     - linux
#     - shell
#     - mysql

- name: install package
  hosts: web
  become: yes
  tasks:
  - name: install package
    ansible.builtin.dnf:
     name: "{{item}}"
     state: latest
    loop:
    - mysql
    - nginx
    - postfix


