- name: configure db server
  hosts: db
  become: yes
  vars:
   login_host: mysql
  vars_prompt:
  - name: mysql_root_password
    prompt: please enter MYSQL root server
    private: no
   
  tasks:
  - name: install mysql server
    ansible.builtin.package:
     name: mysql
     state: latest

  - name: enable service mysql
    ansible.builtin.service:
     name: mysql
     enabled: yes

  - name: start mysql
    ansible.builtin.service:
     name: mysql
     state: started

  - name: install python mysql dependencies
    ansible.builtin.pip:
     name:
     - PYMYSQL
     - cryptography
     executable: pip3.9
     #check password is setup r not

  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{mysql_root_password}}"
      login_host: "{{login_host}}"
    ignore_errors: yes
    register: mysql_connection_output



  - name: print output
    ansible.builtin.debug:
     msg: "output is:{{mysql_connection_output}}"

  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{mysql_root_password}}"
    when: mysql_connection_output.failed is boolean



  




