- name: configure db server
  hosts: db
  become: yes
  vars:
   login_host: mysql

  tasks:
  - name: install mysql server
    ansible.builtin.package:
     name: mysql
     state: latest

  - name: enable service mysql
    ansible.builtin.service:
     name: mysql
     enabled: yes

  - name: start mysql
    ansible.builtin.service:
     name: mysql
     state: started
     #check password is setup r not

  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: Expense@1
      login_host: "{{login_host}}"
      filter: version
    ignore errors: yes
    register: mysql_connection_output


  - name: print output
    ansible.builtin.debug:
     msg: "output is:{{mysql_connection_output}}"

  




